/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The Alert model module.
 * @module model/Alert
 * @version 0.0.0
 */
export class Alert {
  /**
   * Constructs a new <code>Alert</code>.
   * Alert
   * @alias module:model/Alert
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>Alert</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Alert} obj Optional instance to populate.
   * @return {module:model/Alert} The populated <code>Alert</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Alert();
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("idCliente"))
        obj.idCliente = ApiClient.convertToType(data["idCliente"], "Number");
      if (data.hasOwnProperty("idTipoAlojamento"))
        obj.idTipoAlojamento = ApiClient.convertToType(
          data["idTipoAlojamento"],
          "String"
        );
      if (data.hasOwnProperty("idTipo"))
        obj.idTipo = ApiClient.convertToType(data["idTipo"], "String");
      if (data.hasOwnProperty("valor"))
        obj.valor = ApiClient.convertToType(data["valor"], "Number");
      if (data.hasOwnProperty("pessoas"))
        obj.pessoas = ApiClient.convertToType(data["pessoas"], "Number");
      if (data.hasOwnProperty("destino"))
        obj.destino = ApiClient.convertToType(data["destino"], "String");
      if (data.hasOwnProperty("forRent"))
        obj.forRent = ApiClient.convertToType(data["forRent"], "Boolean");
      if (data.hasOwnProperty("forSale"))
        obj.forSale = ApiClient.convertToType(data["forSale"], "Boolean");
      if (data.hasOwnProperty("forArrenda"))
        obj.forArrenda = ApiClient.convertToType(data["forArrenda"], "Boolean");
      if (data.hasOwnProperty("valorArrenda"))
        obj.valorArrenda = ApiClient.convertToType(
          data["valorArrenda"],
          "Number"
        );
      if (data.hasOwnProperty("valorVenda"))
        obj.valorVenda = ApiClient.convertToType(data["valorVenda"], "Number");
      if (data.hasOwnProperty("valorRent"))
        obj.valorRent = ApiClient.convertToType(data["valorRent"], "Number");
      if (data.hasOwnProperty("inicio"))
        obj.inicio = ApiClient.convertToType(data["inicio"], "String");
      if (data.hasOwnProperty("fim"))
        obj.fim = ApiClient.convertToType(data["fim"], "String");
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Alert.prototype.id = undefined;

/**
 * @member {Number} idCliente
 */
Alert.prototype.idCliente = undefined;

/**
 * @member {String} idTipoAlojamento
 */
Alert.prototype.idTipoAlojamento = undefined;

/**
 * @member {String} idTipo
 */
Alert.prototype.idTipo = undefined;

/**
 * @member {Number} valor
 */
Alert.prototype.valor = undefined;

/**
 * @member {Number} pessoas
 */
Alert.prototype.pessoas = undefined;

/**
 * @member {String} destino
 */
Alert.prototype.destino = undefined;

/**
 * @member {Boolean} forRent
 */
Alert.prototype.forRent = undefined;

/**
 * @member {Boolean} forSale
 */
Alert.prototype.forSale = undefined;

/**
 * @member {Boolean} forArrenda
 */
Alert.prototype.forArrenda = undefined;

/**
 * @member {Number} valorArrenda
 */
Alert.prototype.valorArrenda = undefined;

/**
 * @member {Number} valorVenda
 */
Alert.prototype.valorVenda = undefined;

/**
 * @member {Number} valorRent
 */
Alert.prototype.valorRent = undefined;

/**
 * @member {String} inicio
 * @default 'NULL'
 */
Alert.prototype.inicio = "NULL";

/**
 * @member {String} fim
 * @default 'NULL'
 */
Alert.prototype.fim = "NULL";
