/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The Casa model module.
 * @module model/Casa
 * @version 0.0.0
 */
export class Casa {
  /**
   * Constructs a new <code>Casa</code>.
   * Casa
   * @alias module:model/Casa
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>Casa</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Casa} obj Optional instance to populate.
   * @return {module:model/Casa} The populated <code>Casa</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Casa();
      if (data.hasOwnProperty("prereservas"))
        obj.prereservas = ApiClient.convertToType(data["prereservas"], [
          "String",
        ]);
      if (data.hasOwnProperty("owner"))
        obj.owner = ApiClient.convertToType(data["owner"], "String");
      if (data.hasOwnProperty("codCasa"))
        obj.codCasa = ApiClient.convertToType(data["codCasa"], "Number");
      if (data.hasOwnProperty("adicionado"))
        obj.adicionado = ApiClient.convertToType(data["adicionado"], "String");
      if (data.hasOwnProperty("dataActivo"))
        obj.dataActivo = ApiClient.convertToType(data["dataActivo"], "String");
      if (data.hasOwnProperty("destino"))
        obj.destino = ApiClient.convertToType(data["destino"], "String");
      if (data.hasOwnProperty("propid"))
        obj.propid = ApiClient.convertToType(data["propid"], "Number");
      if (data.hasOwnProperty("designacao"))
        obj.designacao = ApiClient.convertToType(data["designacao"], "String");
      if (data.hasOwnProperty("tipoalojamento"))
        obj.tipoalojamento = ApiClient.convertToType(
          data["tipoalojamento"],
          "String"
        );
      if (data.hasOwnProperty("tipo"))
        obj.tipo = ApiClient.convertToType(data["tipo"], "String");
      if (data.hasOwnProperty("pessoas"))
        obj.pessoas = ApiClient.convertToType(data["pessoas"], "Number");
      if (data.hasOwnProperty("pais"))
        obj.pais = ApiClient.convertToType(data["pais"], "String");
      if (data.hasOwnProperty("distrito"))
        obj.distrito = ApiClient.convertToType(data["distrito"], "String");
      if (data.hasOwnProperty("endereco"))
        obj.endereco = ApiClient.convertToType(data["endereco"], "String");
      if (data.hasOwnProperty("codpostal"))
        obj.codpostal = ApiClient.convertToType(data["codpostal"], "String");
      if (data.hasOwnProperty("area"))
        obj.area = ApiClient.convertToType(data["area"], "String");
      if (data.hasOwnProperty("lat"))
        obj.lat = ApiClient.convertToType(data["lat"], "String");
      if (data.hasOwnProperty("lng"))
        obj.lng = ApiClient.convertToType(data["lng"], "String");
      if (data.hasOwnProperty("altitude"))
        obj.altitude = ApiClient.convertToType(data["altitude"], "String");
      if (data.hasOwnProperty("localidade"))
        obj.localidade = ApiClient.convertToType(data["localidade"], "String");
      if (data.hasOwnProperty("distCentro"))
        obj.distCentro = ApiClient.convertToType(data["distCentro"], "String");
      if (data.hasOwnProperty("distPraia"))
        obj.distPraia = ApiClient.convertToType(data["distPraia"], "String");
      if (data.hasOwnProperty("piscina"))
        obj.piscina = ApiClient.convertToType(data["piscina"], "Boolean");
      if (data.hasOwnProperty("televisao"))
        obj.televisao = ApiClient.convertToType(data["televisao"], "Boolean");
      if (data.hasOwnProperty("arCondicionado"))
        obj.arCondicionado = ApiClient.convertToType(
          data["arCondicionado"],
          "Boolean"
        );
      if (data.hasOwnProperty("img1"))
        obj.img1 = ApiClient.convertToType(data["img1"], "String");
      if (data.hasOwnProperty("img2"))
        obj.img2 = ApiClient.convertToType(data["img2"], "String");
      if (data.hasOwnProperty("img3"))
        obj.img3 = ApiClient.convertToType(data["img3"], "String");
      if (data.hasOwnProperty("img4"))
        obj.img4 = ApiClient.convertToType(data["img4"], "String");
      if (data.hasOwnProperty("img5"))
        obj.img5 = ApiClient.convertToType(data["img5"], "String");
      if (data.hasOwnProperty("img6"))
        obj.img6 = ApiClient.convertToType(data["img6"], "String");
      if (data.hasOwnProperty("img7"))
        obj.img7 = ApiClient.convertToType(data["img7"], "String");
      if (data.hasOwnProperty("img8"))
        obj.img8 = ApiClient.convertToType(data["img8"], "String");
      if (data.hasOwnProperty("img9"))
        obj.img9 = ApiClient.convertToType(data["img9"], "String");
      if (data.hasOwnProperty("img10"))
        obj.img10 = ApiClient.convertToType(data["img10"], "String");
      if (data.hasOwnProperty("quartos"))
        obj.quartos = ApiClient.convertToType(data["quartos"], "Number");
      if (data.hasOwnProperty("camascasal"))
        obj.camascasal = ApiClient.convertToType(data["camascasal"], "Number");
      if (data.hasOwnProperty("camassingle"))
        obj.camassingle = ApiClient.convertToType(
          data["camassingle"],
          "Number"
        );
      if (data.hasOwnProperty("casasbanho"))
        obj.casasbanho = ApiClient.convertToType(data["casasbanho"], "Number");
      if (data.hasOwnProperty("golf"))
        obj.golf = ApiClient.convertToType(data["golf"], "Boolean");
      if (data.hasOwnProperty("tenis"))
        obj.tenis = ApiClient.convertToType(data["tenis"], "Boolean");
      if (data.hasOwnProperty("pesca"))
        obj.pesca = ApiClient.convertToType(data["pesca"], "Boolean");
      if (data.hasOwnProperty("natacao"))
        obj.natacao = ApiClient.convertToType(data["natacao"], "Boolean");
      if (data.hasOwnProperty("bowling"))
        obj.bowling = ApiClient.convertToType(data["bowling"], "Boolean");
      if (data.hasOwnProperty("casino"))
        obj.casino = ApiClient.convertToType(data["casino"], "Boolean");
      if (data.hasOwnProperty("cinema"))
        obj.cinema = ApiClient.convertToType(data["cinema"], "Boolean");
      if (data.hasOwnProperty("discoteca"))
        obj.discoteca = ApiClient.convertToType(data["discoteca"], "Boolean");
      if (data.hasOwnProperty("outrasActividprox"))
        obj.outrasActividprox = ApiClient.convertToType(
          data["outrasActividprox"],
          "String"
        );
      if (data.hasOwnProperty("roupascama"))
        obj.roupascama = ApiClient.convertToType(data["roupascama"], "Boolean");
      if (data.hasOwnProperty("roupasbanho"))
        obj.roupasbanho = ApiClient.convertToType(
          data["roupasbanho"],
          "Boolean"
        );
      if (data.hasOwnProperty("limpeza"))
        obj.limpeza = ApiClient.convertToType(data["limpeza"], "Boolean");
      if (data.hasOwnProperty("utilcozinha"))
        obj.utilcozinha = ApiClient.convertToType(
          data["utilcozinha"],
          "Boolean"
        );
      if (data.hasOwnProperty("fogao"))
        obj.fogao = ApiClient.convertToType(data["fogao"], "Boolean");
      if (data.hasOwnProperty("frigorif"))
        obj.frigorif = ApiClient.convertToType(data["frigorif"], "Boolean");
      if (data.hasOwnProperty("congel"))
        obj.congel = ApiClient.convertToType(data["congel"], "Boolean");
      if (data.hasOwnProperty("forno"))
        obj.forno = ApiClient.convertToType(data["forno"], "Boolean");
      if (data.hasOwnProperty("barbecue"))
        obj.barbecue = ApiClient.convertToType(data["barbecue"], "Boolean");
      if (data.hasOwnProperty("microndas"))
        obj.microndas = ApiClient.convertToType(data["microndas"], "Boolean");
      if (data.hasOwnProperty("mlavaloica"))
        obj.mlavaloica = ApiClient.convertToType(data["mlavaloica"], "Boolean");
      if (data.hasOwnProperty("mlavaroupa"))
        obj.mlavaroupa = ApiClient.convertToType(data["mlavaroupa"], "Boolean");
      if (data.hasOwnProperty("aqcentral"))
        obj.aqcentral = ApiClient.convertToType(data["aqcentral"], "Boolean");
      if (data.hasOwnProperty("satcabo"))
        obj.satcabo = ApiClient.convertToType(data["satcabo"], "Boolean");
      if (data.hasOwnProperty("internet"))
        obj.internet = ApiClient.convertToType(data["internet"], "Boolean");
      if (data.hasOwnProperty("outrosServicos"))
        obj.outrosServicos = ApiClient.convertToType(
          data["outrosServicos"],
          "String"
        );
      if (data.hasOwnProperty("linkInfo"))
        obj.linkInfo = ApiClient.convertToType(data["linkInfo"], "String");
      if (data.hasOwnProperty("linkDispon"))
        obj.linkDispon = ApiClient.convertToType(data["linkDispon"], "String");
      if (data.hasOwnProperty("activo"))
        obj.activo = ApiClient.convertToType(data["activo"], "Boolean");
      if (data.hasOwnProperty("sessid"))
        obj.sessid = ApiClient.convertToType(data["sessid"], "String");
      if (data.hasOwnProperty("promo"))
        obj.promo = ApiClient.convertToType(data["promo"], "Boolean");
      if (data.hasOwnProperty("certif"))
        obj.certif = ApiClient.convertToType(data["certif"], "Boolean");
      if (data.hasOwnProperty("dataAct"))
        obj.dataAct = ApiClient.convertToType(data["dataAct"], "String");
      if (data.hasOwnProperty("titulo"))
        obj.titulo = ApiClient.convertToType(data["titulo"], "String");
      if (data.hasOwnProperty("qtspecialoffer"))
        obj.qtspecialoffer = ApiClient.convertToType(
          data["qtspecialoffer"],
          "Number"
        );
      if (data.hasOwnProperty("fengomar"))
        obj.fengomar = ApiClient.convertToType(data["fengomar"], "Boolean");
      if (data.hasOwnProperty("estacionamento"))
        obj.estacionamento = ApiClient.convertToType(
          data["estacionamento"],
          "Boolean"
        );
      if (data.hasOwnProperty("telefone"))
        obj.telefone = ApiClient.convertToType(data["telefone"], "Boolean");
      if (data.hasOwnProperty("despertador"))
        obj.despertador = ApiClient.convertToType(
          data["despertador"],
          "Boolean"
        );
      if (data.hasOwnProperty("dvd"))
        obj.dvd = ApiClient.convertToType(data["dvd"], "Boolean");
      if (data.hasOwnProperty("torradeira"))
        obj.torradeira = ApiClient.convertToType(data["torradeira"], "Boolean");
      if (data.hasOwnProperty("animais"))
        obj.animais = ApiClient.convertToType(data["animais"], "Boolean");
      if (data.hasOwnProperty("fumadores"))
        obj.fumadores = ApiClient.convertToType(data["fumadores"], "Boolean");
      if (data.hasOwnProperty("caucao"))
        obj.caucao = ApiClient.convertToType(data["caucao"], "Boolean");
      if (data.hasOwnProperty("valorcaucao"))
        obj.valorcaucao = ApiClient.convertToType(
          data["valorcaucao"],
          "String"
        );
      if (data.hasOwnProperty("deficientes"))
        obj.deficientes = ApiClient.convertToType(
          data["deficientes"],
          "String"
        );
      if (data.hasOwnProperty("concelho"))
        obj.concelho = ApiClient.convertToType(data["concelho"], "String");
      if (data.hasOwnProperty("altImg1"))
        obj.altImg1 = ApiClient.convertToType(data["altImg1"], "String");
      if (data.hasOwnProperty("forSale"))
        obj.forSale = ApiClient.convertToType(data["forSale"], "Boolean");
      if (data.hasOwnProperty("forRent"))
        obj.forRent = ApiClient.convertToType(data["forRent"], "Boolean");
      if (data.hasOwnProperty("forArrenda"))
        obj.forArrenda = ApiClient.convertToType(data["forArrenda"], "Boolean");
      if (data.hasOwnProperty("valorArrendamento"))
        obj.valorArrendamento = ApiClient.convertToType(
          data["valorArrendamento"],
          "Number"
        );
      if (data.hasOwnProperty("valorVenda"))
        obj.valorVenda = ApiClient.convertToType(data["valorVenda"], "Number");
      if (data.hasOwnProperty("certifEnerg"))
        obj.certifEnerg = ApiClient.convertToType(
          data["certifEnerg"],
          "Boolean"
        );
      if (data.hasOwnProperty("certifEnergLevel"))
        obj.certifEnergLevel = ApiClient.convertToType(
          data["certifEnergLevel"],
          "String"
        );
      if (data.hasOwnProperty("seoTitle"))
        obj.seoTitle = ApiClient.convertToType(data["seoTitle"], "String");
      if (data.hasOwnProperty("ano"))
        obj.ano = ApiClient.convertToType(data["ano"], "Number");
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} prereservas
 */
Casa.prototype.prereservas = undefined;

/**
 * @member {String} owner
 */
Casa.prototype.owner = undefined;

/**
 * @member {Number} codCasa
 */
Casa.prototype.codCasa = undefined;

/**
 * @member {String} adicionado
 * @default 'NULL'
 */
Casa.prototype.adicionado = "NULL";

/**
 * @member {String} dataActivo
 * @default 'NULL'
 */
Casa.prototype.dataActivo = "NULL";

/**
 * @member {String} destino
 * @default 'NULL'
 */
Casa.prototype.destino = "NULL";

/**
 * @member {Number} propid
 */
Casa.prototype.propid = undefined;

/**
 * @member {String} designacao
 * @default 'NULL'
 */
Casa.prototype.designacao = "NULL";

/**
 * @member {String} tipoalojamento
 * @default 'NULL'
 */
Casa.prototype.tipoalojamento = "NULL";

/**
 * @member {String} tipo
 * @default 'NULL'
 */
Casa.prototype.tipo = "NULL";

/**
 * @member {Number} pessoas
 */
Casa.prototype.pessoas = undefined;

/**
 * @member {String} pais
 * @default 'NULL'
 */
Casa.prototype.pais = "NULL";

/**
 * @member {String} distrito
 * @default 'NULL'
 */
Casa.prototype.distrito = "NULL";

/**
 * @member {String} endereco
 * @default 'NULL'
 */
Casa.prototype.endereco = "NULL";

/**
 * @member {String} codpostal
 * @default 'NULL'
 */
Casa.prototype.codpostal = "NULL";

/**
 * @member {String} area
 * @default 'NULL'
 */
Casa.prototype.area = "NULL";

/**
 * @member {String} lat
 * @default 'NULL'
 */
Casa.prototype.lat = "NULL";

/**
 * @member {String} lng
 * @default 'NULL'
 */
Casa.prototype.lng = "NULL";

/**
 * @member {String} altitude
 * @default 'NULL'
 */
Casa.prototype.altitude = "NULL";

/**
 * @member {String} localidade
 * @default 'NULL'
 */
Casa.prototype.localidade = "NULL";

/**
 * @member {String} distCentro
 * @default 'NULL'
 */
Casa.prototype.distCentro = "NULL";

/**
 * @member {String} distPraia
 * @default 'NULL'
 */
Casa.prototype.distPraia = "NULL";

/**
 * @member {Boolean} piscina
 * @default false
 */
Casa.prototype.piscina = false;

/**
 * @member {Boolean} televisao
 * @default false
 */
Casa.prototype.televisao = false;

/**
 * @member {Boolean} arCondicionado
 * @default false
 */
Casa.prototype.arCondicionado = false;

/**
 * @member {String} img1
 * @default 'images/noimage.jpg'
 */
Casa.prototype.img1 = "images/noimage.jpg";

/**
 * @member {String} img2
 * @default 'images/noimage.jpg'
 */
Casa.prototype.img2 = "images/noimage.jpg";

/**
 * @member {String} img3
 * @default 'images/noimage.jpg'
 */
Casa.prototype.img3 = "images/noimage.jpg";

/**
 * @member {String} img4
 * @default 'images/noimage.jpg'
 */
Casa.prototype.img4 = "images/noimage.jpg";

/**
 * @member {String} img5
 * @default 'images/noimage.jpg'
 */
Casa.prototype.img5 = "images/noimage.jpg";

/**
 * @member {String} img6
 * @default 'images/noimage.jpg'
 */
Casa.prototype.img6 = "images/noimage.jpg";

/**
 * @member {String} img7
 * @default 'images/noimage.jpg'
 */
Casa.prototype.img7 = "images/noimage.jpg";

/**
 * @member {String} img8
 * @default 'images/noimage.jpg'
 */
Casa.prototype.img8 = "images/noimage.jpg";

/**
 * @member {String} img9
 * @default 'images/noimage.jpg'
 */
Casa.prototype.img9 = "images/noimage.jpg";

/**
 * @member {String} img10
 * @default 'images/noimage.jpg'
 */
Casa.prototype.img10 = "images/noimage.jpg";

/**
 * @member {Number} quartos
 */
Casa.prototype.quartos = undefined;

/**
 * @member {Number} camascasal
 */
Casa.prototype.camascasal = undefined;

/**
 * @member {Number} camassingle
 */
Casa.prototype.camassingle = undefined;

/**
 * @member {Number} casasbanho
 */
Casa.prototype.casasbanho = undefined;

/**
 * @member {Boolean} golf
 * @default false
 */
Casa.prototype.golf = false;

/**
 * @member {Boolean} tenis
 * @default false
 */
Casa.prototype.tenis = false;

/**
 * @member {Boolean} pesca
 * @default false
 */
Casa.prototype.pesca = false;

/**
 * @member {Boolean} natacao
 * @default false
 */
Casa.prototype.natacao = false;

/**
 * @member {Boolean} bowling
 * @default false
 */
Casa.prototype.bowling = false;

/**
 * @member {Boolean} casino
 * @default false
 */
Casa.prototype.casino = false;

/**
 * @member {Boolean} cinema
 * @default false
 */
Casa.prototype.cinema = false;

/**
 * @member {Boolean} discoteca
 * @default false
 */
Casa.prototype.discoteca = false;

/**
 * @member {String} outrasActividprox
 * @default 'NULL'
 */
Casa.prototype.outrasActividprox = "NULL";

/**
 * @member {Boolean} roupascama
 * @default false
 */
Casa.prototype.roupascama = false;

/**
 * @member {Boolean} roupasbanho
 * @default false
 */
Casa.prototype.roupasbanho = false;

/**
 * @member {Boolean} limpeza
 * @default false
 */
Casa.prototype.limpeza = false;

/**
 * @member {Boolean} utilcozinha
 * @default false
 */
Casa.prototype.utilcozinha = false;

/**
 * @member {Boolean} fogao
 * @default false
 */
Casa.prototype.fogao = false;

/**
 * @member {Boolean} frigorif
 * @default false
 */
Casa.prototype.frigorif = false;

/**
 * @member {Boolean} congel
 * @default false
 */
Casa.prototype.congel = false;

/**
 * @member {Boolean} forno
 * @default false
 */
Casa.prototype.forno = false;

/**
 * @member {Boolean} barbecue
 * @default false
 */
Casa.prototype.barbecue = false;

/**
 * @member {Boolean} microndas
 * @default false
 */
Casa.prototype.microndas = false;

/**
 * @member {Boolean} mlavaloica
 * @default false
 */
Casa.prototype.mlavaloica = false;

/**
 * @member {Boolean} mlavaroupa
 * @default false
 */
Casa.prototype.mlavaroupa = false;

/**
 * @member {Boolean} aqcentral
 * @default false
 */
Casa.prototype.aqcentral = false;

/**
 * @member {Boolean} satcabo
 * @default false
 */
Casa.prototype.satcabo = false;

/**
 * @member {Boolean} internet
 * @default false
 */
Casa.prototype.internet = false;

/**
 * @member {String} outrosServicos
 * @default 'NULL'
 */
Casa.prototype.outrosServicos = "NULL";

/**
 * @member {String} linkInfo
 * @default 'NULL'
 */
Casa.prototype.linkInfo = "NULL";

/**
 * @member {String} linkDispon
 * @default 'NULL'
 */
Casa.prototype.linkDispon = "NULL";

/**
 * @member {Boolean} activo
 * @default false
 */
Casa.prototype.activo = false;

/**
 * @member {String} sessid
 * @default 'NULL'
 */
Casa.prototype.sessid = "NULL";

/**
 * @member {Boolean} promo
 * @default false
 */
Casa.prototype.promo = false;

/**
 * @member {Boolean} certif
 * @default false
 */
Casa.prototype.certif = false;

/**
 * @member {String} dataAct
 * @default 'NULL'
 */
Casa.prototype.dataAct = "NULL";

/**
 * @member {String} titulo
 * @default 'NULL'
 */
Casa.prototype.titulo = "NULL";

/**
 * @member {Number} qtspecialoffer
 */
Casa.prototype.qtspecialoffer = undefined;

/**
 * @member {Boolean} fengomar
 * @default false
 */
Casa.prototype.fengomar = false;

/**
 * @member {Boolean} estacionamento
 * @default false
 */
Casa.prototype.estacionamento = false;

/**
 * @member {Boolean} telefone
 * @default false
 */
Casa.prototype.telefone = false;

/**
 * @member {Boolean} despertador
 * @default false
 */
Casa.prototype.despertador = false;

/**
 * @member {Boolean} dvd
 * @default false
 */
Casa.prototype.dvd = false;

/**
 * @member {Boolean} torradeira
 * @default false
 */
Casa.prototype.torradeira = false;

/**
 * @member {Boolean} animais
 * @default false
 */
Casa.prototype.animais = false;

/**
 * @member {Boolean} fumadores
 * @default false
 */
Casa.prototype.fumadores = false;

/**
 * @member {Boolean} caucao
 * @default false
 */
Casa.prototype.caucao = false;

/**
 * @member {String} valorcaucao
 * @default 'NULL'
 */
Casa.prototype.valorcaucao = "NULL";

/**
 * @member {String} deficientes
 * @default 'NULL'
 */
Casa.prototype.deficientes = "NULL";

/**
 * @member {String} concelho
 * @default 'NULL'
 */
Casa.prototype.concelho = "NULL";

/**
 * @member {String} altImg1
 * @default 'NULL'
 */
Casa.prototype.altImg1 = "NULL";

/**
 * @member {Boolean} forSale
 */
Casa.prototype.forSale = undefined;

/**
 * @member {Boolean} forRent
 */
Casa.prototype.forRent = undefined;

/**
 * @member {Boolean} forArrenda
 */
Casa.prototype.forArrenda = undefined;

/**
 * @member {Number} valorArrendamento
 */
Casa.prototype.valorArrendamento = undefined;

/**
 * @member {Number} valorVenda
 */
Casa.prototype.valorVenda = undefined;

/**
 * @member {Boolean} certifEnerg
 */
Casa.prototype.certifEnerg = undefined;

/**
 * @member {String} certifEnergLevel
 */
Casa.prototype.certifEnergLevel = undefined;

/**
 * @member {String} seoTitle
 */
Casa.prototype.seoTitle = undefined;

/**
 * @member {Number} ano
 */
Casa.prototype.ano = undefined;
