/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The Feedbackcoment model module.
 * @module model/Feedbackcoment
 * @version 0.0.0
 */
export class Feedbackcoment {
  /**
   * Constructs a new <code>Feedbackcoment</code>.
   * Feedbackcoment
   * @alias module:model/Feedbackcoment
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>Feedbackcoment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Feedbackcoment} obj Optional instance to populate.
   * @return {module:model/Feedbackcoment} The populated <code>Feedbackcoment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Feedbackcoment();
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("codCasa"))
        obj.codCasa = ApiClient.convertToType(data["codCasa"], "Number");
      if (data.hasOwnProperty("coment"))
        obj.coment = ApiClient.convertToType(data["coment"], "String");
      if (data.hasOwnProperty("valorVoto"))
        obj.valorVoto = ApiClient.convertToType(data["valorVoto"], "Number");
      if (data.hasOwnProperty("reserva"))
        obj.reserva = ApiClient.convertToType(data["reserva"], "Number");
      if (data.hasOwnProperty("nome"))
        obj.nome = ApiClient.convertToType(data["nome"], "String");
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Feedbackcoment.prototype.id = undefined;

/**
 * @member {Number} codCasa
 */
Feedbackcoment.prototype.codCasa = undefined;

/**
 * @member {String} coment
 * @default 'NULL'
 */
Feedbackcoment.prototype.coment = "NULL";

/**
 * @member {Number} valorVoto
 */
Feedbackcoment.prototype.valorVoto = undefined;

/**
 * @member {Number} reserva
 */
Feedbackcoment.prototype.reserva = undefined;

/**
 * @member {String} nome
 * @default 'NULL'
 */
Feedbackcoment.prototype.nome = "NULL";
