/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The FeedbackJsonld model module.
 * @module model/FeedbackJsonld
 * @version 0.0.0
 */
export class FeedbackJsonld {
  /**
   * Constructs a new <code>FeedbackJsonld</code>.
   * Feedback
   * @alias module:model/FeedbackJsonld
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>FeedbackJsonld</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FeedbackJsonld} obj Optional instance to populate.
   * @return {module:model/FeedbackJsonld} The populated <code>FeedbackJsonld</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FeedbackJsonld();
      if (data.hasOwnProperty("@context"))
        obj.context = ApiClient.convertToType(data["@context"], Object);
      if (data.hasOwnProperty("@id"))
        obj.id = ApiClient.convertToType(data["@id"], "String");
      if (data.hasOwnProperty("@type"))
        obj.type = ApiClient.convertToType(data["@type"], "String");
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("codCasa"))
        obj.codCasa = ApiClient.convertToType(data["codCasa"], "Number");
      if (data.hasOwnProperty("valorVoto"))
        obj.valorVoto = ApiClient.convertToType(data["valorVoto"], "Number");
      if (data.hasOwnProperty("comment"))
        obj.comment = ApiClient.convertToType(data["comment"], "String");
      if (data.hasOwnProperty("idCliente"))
        obj.idCliente = ApiClient.convertToType(data["idCliente"], "Number");
      if (data.hasOwnProperty("reserva"))
        obj.reserva = ApiClient.convertToType(data["reserva"], "Number");
      if (data.hasOwnProperty("revisto"))
        obj.revisto = ApiClient.convertToType(data["revisto"], "Boolean");
      if (data.hasOwnProperty("aproved"))
        obj.aproved = ApiClient.convertToType(data["aproved"], "Boolean");
    }
    return obj;
  }
}

/**
 * @member {Object} context
 */
FeedbackJsonld.prototype.context = undefined;

/**
 * @member {String} id
 */
FeedbackJsonld.prototype.id = undefined;

/**
 * @member {String} type
 */
FeedbackJsonld.prototype.type = undefined;

/**
 * @member {Number} id
 */
FeedbackJsonld.prototype.id = undefined;

/**
 * @member {Number} codCasa
 */
FeedbackJsonld.prototype.codCasa = undefined;

/**
 * @member {Number} valorVoto
 */
FeedbackJsonld.prototype.valorVoto = undefined;

/**
 * @member {String} comment
 */
FeedbackJsonld.prototype.comment = undefined;

/**
 * @member {Number} idCliente
 */
FeedbackJsonld.prototype.idCliente = undefined;

/**
 * @member {Number} reserva
 */
FeedbackJsonld.prototype.reserva = undefined;

/**
 * @member {Boolean} revisto
 */
FeedbackJsonld.prototype.revisto = undefined;

/**
 * @member {Boolean} aproved
 */
FeedbackJsonld.prototype.aproved = undefined;
