/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The Mylist model module.
 * @module model/Mylist
 * @version 0.0.0
 */
export class Mylist {
  /**
   * Constructs a new <code>Mylist</code>.
   * Mylist
   * @alias module:model/Mylist
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>Mylist</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Mylist} obj Optional instance to populate.
   * @return {module:model/Mylist} The populated <code>Mylist</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Mylist();
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("codCasa"))
        obj.codCasa = ApiClient.convertToType(data["codCasa"], "Number");
      if (data.hasOwnProperty("mylistcol"))
        obj.mylistcol = ApiClient.convertToType(data["mylistcol"], "String");
      if (data.hasOwnProperty("sessid"))
        obj.sessid = ApiClient.convertToType(data["sessid"], "String");
      if (data.hasOwnProperty("cliente"))
        obj.cliente = ApiClient.convertToType(data["cliente"], "String");
      if (data.hasOwnProperty("data"))
        obj.data = ApiClient.convertToType(data["data"], "String");
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Mylist.prototype.id = undefined;

/**
 * @member {Number} codCasa
 */
Mylist.prototype.codCasa = undefined;

/**
 * @member {String} mylistcol
 * @default 'NULL'
 */
Mylist.prototype.mylistcol = "NULL";

/**
 * @member {String} sessid
 * @default 'NULL'
 */
Mylist.prototype.sessid = "NULL";

/**
 * @member {String} cliente
 * @default 'NULL'
 */
Mylist.prototype.cliente = "NULL";

/**
 * @member {String} data
 * @default 'NULL'
 */
Mylist.prototype.data = "NULL";
