/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The OneOfCasaJsonldContext model module.
 * @module model/OneOfCasaJsonldContext
 * @version 0.0.0
 */
export class OneOfCasaJsonldContext {
  /**
   * Constructs a new <code>OneOfCasaJsonldContext</code>.
   * @alias module:model/OneOfCasaJsonldContext
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>OneOfCasaJsonldContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OneOfCasaJsonldContext} obj Optional instance to populate.
   * @return {module:model/OneOfCasaJsonldContext} The populated <code>OneOfCasaJsonldContext</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OneOfCasaJsonldContext();
    }
    return obj;
  }
}
