/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The OneOfPrereservaJsonldContext model module.
 * @module model/OneOfPrereservaJsonldContext
 * @version 0.0.0
 */
export class OneOfPrereservaJsonldContext {
  /**
   * Constructs a new <code>OneOfPrereservaJsonldContext</code>.
   * @alias module:model/OneOfPrereservaJsonldContext
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>OneOfPrereservaJsonldContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OneOfPrereservaJsonldContext} obj Optional instance to populate.
   * @return {module:model/OneOfPrereservaJsonldContext} The populated <code>OneOfPrereservaJsonldContext</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OneOfPrereservaJsonldContext();
    }
    return obj;
  }
}
