/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The Periodo model module.
 * @module model/Periodo
 * @version 0.0.0
 */
export class Periodo {
  /**
   * Constructs a new <code>Periodo</code>.
   * Periodo
   * @alias module:model/Periodo
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>Periodo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Periodo} obj Optional instance to populate.
   * @return {module:model/Periodo} The populated <code>Periodo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Periodo();
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("codCasa"))
        obj.codCasa = ApiClient.convertToType(data["codCasa"], "Number");
      if (data.hasOwnProperty("inicio"))
        obj.inicio = ApiClient.convertToType(data["inicio"], "String");
      if (data.hasOwnProperty("fim"))
        obj.fim = ApiClient.convertToType(data["fim"], "String");
      if (data.hasOwnProperty("precoSemana"))
        obj.precoSemana = ApiClient.convertToType(
          data["precoSemana"],
          "String"
        );
      if (data.hasOwnProperty("precoDia"))
        obj.precoDia = ApiClient.convertToType(data["precoDia"], "String");
      if (data.hasOwnProperty("precoFimsemana"))
        obj.precoFimsemana = ApiClient.convertToType(
          data["precoFimsemana"],
          "String"
        );
      if (data.hasOwnProperty("estadiaMinima"))
        obj.estadiaMinima = ApiClient.convertToType(
          data["estadiaMinima"],
          "String"
        );
      if (data.hasOwnProperty("descricao"))
        obj.descricao = ApiClient.convertToType(data["descricao"], "String");
      if (data.hasOwnProperty("observacoes"))
        obj.observacoes = ApiClient.convertToType(
          data["observacoes"],
          "String"
        );
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Periodo.prototype.id = undefined;

/**
 * @member {Number} codCasa
 */
Periodo.prototype.codCasa = undefined;

/**
 * @member {String} inicio
 */
Periodo.prototype.inicio = undefined;

/**
 * @member {String} fim
 */
Periodo.prototype.fim = undefined;

/**
 * @member {String} precoSemana
 */
Periodo.prototype.precoSemana = undefined;

/**
 * @member {String} precoDia
 */
Periodo.prototype.precoDia = undefined;

/**
 * @member {String} precoFimsemana
 */
Periodo.prototype.precoFimsemana = undefined;

/**
 * @member {String} estadiaMinima
 */
Periodo.prototype.estadiaMinima = undefined;

/**
 * @member {String} descricao
 * @default 'NULL'
 */
Periodo.prototype.descricao = "NULL";

/**
 * @member {String} observacoes
 */
Periodo.prototype.observacoes = undefined;
