/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The PeriodoLongoJsonld model module.
 * @module model/PeriodoLongoJsonld
 * @version 0.0.0
 */
export class PeriodoLongoJsonld {
  /**
   * Constructs a new <code>PeriodoLongoJsonld</code>.
   * PeriodoLongo
   * @alias module:model/PeriodoLongoJsonld
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>PeriodoLongoJsonld</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PeriodoLongoJsonld} obj Optional instance to populate.
   * @return {module:model/PeriodoLongoJsonld} The populated <code>PeriodoLongoJsonld</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PeriodoLongoJsonld();
      if (data.hasOwnProperty("@context"))
        obj.context = ApiClient.convertToType(data["@context"], Object);
      if (data.hasOwnProperty("@id"))
        obj.id = ApiClient.convertToType(data["@id"], "String");
      if (data.hasOwnProperty("@type"))
        obj.type = ApiClient.convertToType(data["@type"], "String");
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("inicio"))
        obj.inicio = ApiClient.convertToType(data["inicio"], "String");
      if (data.hasOwnProperty("fim"))
        obj.fim = ApiClient.convertToType(data["fim"], "String");
      if (data.hasOwnProperty("precoMes"))
        obj.precoMes = ApiClient.convertToType(data["precoMes"], "Number");
      if (data.hasOwnProperty("estadiaMinima"))
        obj.estadiaMinima = ApiClient.convertToType(
          data["estadiaMinima"],
          "String"
        );
      if (data.hasOwnProperty("codCasa"))
        obj.codCasa = ApiClient.convertToType(data["codCasa"], "String");
    }
    return obj;
  }
}

/**
 * @member {Object} context
 */
PeriodoLongoJsonld.prototype.context = undefined;

/**
 * @member {String} id
 */
PeriodoLongoJsonld.prototype.id = undefined;

/**
 * @member {String} type
 */
PeriodoLongoJsonld.prototype.type = undefined;

/**
 * @member {Number} id
 */
PeriodoLongoJsonld.prototype.id = undefined;

/**
 * @member {String} inicio
 */
PeriodoLongoJsonld.prototype.inicio = undefined;

/**
 * @member {String} fim
 */
PeriodoLongoJsonld.prototype.fim = undefined;

/**
 * @member {Number} precoMes
 */
PeriodoLongoJsonld.prototype.precoMes = undefined;

/**
 * @member {String} estadiaMinima
 */
PeriodoLongoJsonld.prototype.estadiaMinima = undefined;

/**
 * @member {String} codCasa
 */
PeriodoLongoJsonld.prototype.codCasa = undefined;
