/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The Preco model module.
 * @module model/Preco
 * @version 0.0.0
 */
export class Preco {
  /**
   * Constructs a new <code>Preco</code>.
   * Preco
   * @alias module:model/Preco
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>Preco</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Preco} obj Optional instance to populate.
   * @return {module:model/Preco} The populated <code>Preco</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Preco();
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("ano"))
        obj.ano = ApiClient.convertToType(data["ano"], "Number");
      if (data.hasOwnProperty("nmMes"))
        obj.nmMes = ApiClient.convertToType(data["nmMes"], "String");
      if (data.hasOwnProperty("nSemana"))
        obj.nSemana = ApiClient.convertToType(data["nSemana"], "Number");
      if (data.hasOwnProperty("codCasa"))
        obj.codCasa = ApiClient.convertToType(data["codCasa"], "Number");
      if (data.hasOwnProperty("inicio"))
        obj.inicio = ApiClient.convertToType(data["inicio"], "String");
      if (data.hasOwnProperty("fim"))
        obj.fim = ApiClient.convertToType(data["fim"], "String");
      if (data.hasOwnProperty("preco"))
        obj.preco = ApiClient.convertToType(data["preco"], "String");
      if (data.hasOwnProperty("livre"))
        obj.livre = ApiClient.convertToType(data["livre"], "Boolean");
      if (data.hasOwnProperty("reservar"))
        obj.reservar = ApiClient.convertToType(data["reservar"], "String");
      if (data.hasOwnProperty("promo"))
        obj.promo = ApiClient.convertToType(data["promo"], "Boolean");
      if (data.hasOwnProperty("paga"))
        obj.paga = ApiClient.convertToType(data["paga"], "Boolean");
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Preco.prototype.id = undefined;

/**
 * @member {Number} ano
 */
Preco.prototype.ano = undefined;

/**
 * @member {String} nmMes
 * @default 'NULL'
 */
Preco.prototype.nmMes = "NULL";

/**
 * @member {Number} nSemana
 */
Preco.prototype.nSemana = undefined;

/**
 * @member {Number} codCasa
 */
Preco.prototype.codCasa = undefined;

/**
 * @member {String} inicio
 * @default 'NULL'
 */
Preco.prototype.inicio = "NULL";

/**
 * @member {String} fim
 * @default 'NULL'
 */
Preco.prototype.fim = "NULL";

/**
 * @member {String} preco
 * @default 'NULL'
 */
Preco.prototype.preco = "NULL";

/**
 * @member {Boolean} livre
 * @default false
 */
Preco.prototype.livre = false;

/**
 * @member {String} reservar
 * @default 'NULL'
 */
Preco.prototype.reservar = "NULL";

/**
 * @member {Boolean} promo
 * @default false
 */
Preco.prototype.promo = false;

/**
 * @member {Boolean} paga
 * @default false
 */
Preco.prototype.paga = false;
