/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The PrereservaJsonld model module.
 * @module model/PrereservaJsonld
 * @version 0.0.0
 */
export class PrereservaJsonld {
  /**
   * Constructs a new <code>PrereservaJsonld</code>.
   * Prereserva
   * @alias module:model/PrereservaJsonld
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>PrereservaJsonld</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrereservaJsonld} obj Optional instance to populate.
   * @return {module:model/PrereservaJsonld} The populated <code>PrereservaJsonld</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrereservaJsonld();
      if (data.hasOwnProperty("@context"))
        obj.context = ApiClient.convertToType(data["@context"], Object);
      if (data.hasOwnProperty("@id"))
        obj.id = ApiClient.convertToType(data["@id"], "String");
      if (data.hasOwnProperty("@type"))
        obj.type = ApiClient.convertToType(data["@type"], "String");
      if (data.hasOwnProperty("casa"))
        obj.casa = ApiClient.convertToType(data["casa"], "String");
      if (data.hasOwnProperty("nPrereserva"))
        obj.nPrereserva = ApiClient.convertToType(
          data["nPrereserva"],
          "Number"
        );
      if (data.hasOwnProperty("data"))
        obj.data = ApiClient.convertToType(data["data"], "String");
      if (data.hasOwnProperty("expira"))
        obj.expira = ApiClient.convertToType(data["expira"], "String");
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "String");
      if (data.hasOwnProperty("codCasa"))
        obj.codCasa = ApiClient.convertToType(data["codCasa"], "String");
      if (data.hasOwnProperty("nmMes"))
        obj.nmMes = ApiClient.convertToType(data["nmMes"], "String");
      if (data.hasOwnProperty("nSemana"))
        obj.nSemana = ApiClient.convertToType(data["nSemana"], "String");
      if (data.hasOwnProperty("inicio"))
        obj.inicio = ApiClient.convertToType(data["inicio"], "String");
      if (data.hasOwnProperty("fim"))
        obj.fim = ApiClient.convertToType(data["fim"], "String");
      if (data.hasOwnProperty("preco"))
        obj.preco = ApiClient.convertToType(data["preco"], "String");
      if (data.hasOwnProperty("quinzena"))
        obj.quinzena = ApiClient.convertToType(data["quinzena"], "String");
      if (data.hasOwnProperty("nome"))
        obj.nome = ApiClient.convertToType(data["nome"], "String");
      if (data.hasOwnProperty("morada"))
        obj.morada = ApiClient.convertToType(data["morada"], "String");
      if (data.hasOwnProperty("email"))
        obj.email = ApiClient.convertToType(data["email"], "String");
      if (data.hasOwnProperty("telefone"))
        obj.telefone = ApiClient.convertToType(data["telefone"], "String");
      if (data.hasOwnProperty("perguntas"))
        obj.perguntas = ApiClient.convertToType(data["perguntas"], "String");
      if (data.hasOwnProperty("sugestoes"))
        obj.sugestoes = ApiClient.convertToType(data["sugestoes"], "String");
      if (data.hasOwnProperty("comentarios"))
        obj.comentarios = ApiClient.convertToType(
          data["comentarios"],
          "String"
        );
      if (data.hasOwnProperty("situacao"))
        obj.situacao = ApiClient.convertToType(data["situacao"], "String");
      if (data.hasOwnProperty("formaPagamento"))
        obj.formaPagamento = ApiClient.convertToType(
          data["formaPagamento"],
          "Number"
        );
      if (data.hasOwnProperty("valor"))
        obj.valor = ApiClient.convertToType(data["valor"], "Number");
      if (data.hasOwnProperty("sessionid"))
        obj.sessionid = ApiClient.convertToType(data["sessionid"], "String");
      if (data.hasOwnProperty("voto"))
        obj.voto = ApiClient.convertToType(data["voto"], "Boolean");
    }
    return obj;
  }
}

/**
 * @member {Object} context
 */
PrereservaJsonld.prototype.context = undefined;

/**
 * @member {String} id
 */
PrereservaJsonld.prototype.id = undefined;

/**
 * @member {String} type
 */
PrereservaJsonld.prototype.type = undefined;

/**
 * @member {String} casa
 */
PrereservaJsonld.prototype.casa = undefined;

/**
 * @member {Number} nPrereserva
 */
PrereservaJsonld.prototype.nPrereserva = undefined;

/**
 * @member {String} data
 * @default 'NULL'
 */
PrereservaJsonld.prototype.data = "NULL";

/**
 * @member {String} expira
 * @default 'NULL'
 */
PrereservaJsonld.prototype.expira = "NULL";

/**
 * @member {String} id
 * @default 'NULL'
 */
PrereservaJsonld.prototype.id = "NULL";

/**
 * @member {String} codCasa
 * @default 'NULL'
 */
PrereservaJsonld.prototype.codCasa = "NULL";

/**
 * @member {String} nmMes
 * @default 'NULL'
 */
PrereservaJsonld.prototype.nmMes = "NULL";

/**
 * @member {String} nSemana
 * @default 'NULL'
 */
PrereservaJsonld.prototype.nSemana = "NULL";

/**
 * @member {String} inicio
 * @default 'NULL'
 */
PrereservaJsonld.prototype.inicio = "NULL";

/**
 * @member {String} fim
 * @default 'NULL'
 */
PrereservaJsonld.prototype.fim = "NULL";

/**
 * @member {String} preco
 * @default 'NULL'
 */
PrereservaJsonld.prototype.preco = "NULL";

/**
 * @member {String} quinzena
 * @default 'NULL'
 */
PrereservaJsonld.prototype.quinzena = "NULL";

/**
 * @member {String} nome
 * @default 'NULL'
 */
PrereservaJsonld.prototype.nome = "NULL";

/**
 * @member {String} morada
 * @default 'NULL'
 */
PrereservaJsonld.prototype.morada = "NULL";

/**
 * @member {String} email
 * @default 'NULL'
 */
PrereservaJsonld.prototype.email = "NULL";

/**
 * @member {String} telefone
 * @default 'NULL'
 */
PrereservaJsonld.prototype.telefone = "NULL";

/**
 * @member {String} perguntas
 * @default 'NULL'
 */
PrereservaJsonld.prototype.perguntas = "NULL";

/**
 * @member {String} sugestoes
 * @default 'NULL'
 */
PrereservaJsonld.prototype.sugestoes = "NULL";

/**
 * @member {String} comentarios
 * @default 'NULL'
 */
PrereservaJsonld.prototype.comentarios = "NULL";

/**
 * @member {String} situacao
 * @default 'NULL'
 */
PrereservaJsonld.prototype.situacao = "NULL";

/**
 * @member {Number} formaPagamento
 */
PrereservaJsonld.prototype.formaPagamento = undefined;

/**
 * @member {Number} valor
 */
PrereservaJsonld.prototype.valor = undefined;

/**
 * @member {String} sessionid
 * @default 'NULL'
 */
PrereservaJsonld.prototype.sessionid = "NULL";

/**
 * @member {Boolean} voto
 * @default false
 */
PrereservaJsonld.prototype.voto = false;
