/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The ReservaPaymentJsonld model module.
 * @module model/ReservaPaymentJsonld
 * @version 0.0.0
 */
export class ReservaPaymentJsonld {
  /**
   * Constructs a new <code>ReservaPaymentJsonld</code>.
   * ReservaPayment
   * @alias module:model/ReservaPaymentJsonld
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>ReservaPaymentJsonld</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReservaPaymentJsonld} obj Optional instance to populate.
   * @return {module:model/ReservaPaymentJsonld} The populated <code>ReservaPaymentJsonld</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReservaPaymentJsonld();
      if (data.hasOwnProperty("@context"))
        obj.context = ApiClient.convertToType(data["@context"], Object);
      if (data.hasOwnProperty("@id"))
        obj.id = ApiClient.convertToType(data["@id"], "String");
      if (data.hasOwnProperty("@type"))
        obj.type = ApiClient.convertToType(data["@type"], "String");
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("idPagamento"))
        obj.idPagamento = ApiClient.convertToType(
          data["idPagamento"],
          "String"
        );
      if (data.hasOwnProperty("idTipoPagamento"))
        obj.idTipoPagamento = ApiClient.convertToType(
          data["idTipoPagamento"],
          "String"
        );
      if (data.hasOwnProperty("valor"))
        obj.valor = ApiClient.convertToType(data["valor"], "Number");
      if (data.hasOwnProperty("idpreco"))
        obj.idpreco = ApiClient.convertToType(data["idpreco"], "Number");
      if (data.hasOwnProperty("idreserva"))
        obj.idreserva = ApiClient.convertToType(data["idreserva"], "Number");
      if (data.hasOwnProperty("data"))
        obj.data = ApiClient.convertToType(data["data"], "Date");
    }
    return obj;
  }
}

/**
 * @member {Object} context
 */
ReservaPaymentJsonld.prototype.context = undefined;

/**
 * @member {String} id
 */
ReservaPaymentJsonld.prototype.id = undefined;

/**
 * @member {String} type
 */
ReservaPaymentJsonld.prototype.type = undefined;

/**
 * @member {Number} id
 */
ReservaPaymentJsonld.prototype.id = undefined;

/**
 * @member {String} idPagamento
 */
ReservaPaymentJsonld.prototype.idPagamento = undefined;

/**
 * @member {String} idTipoPagamento
 */
ReservaPaymentJsonld.prototype.idTipoPagamento = undefined;

/**
 * @member {Number} valor
 */
ReservaPaymentJsonld.prototype.valor = undefined;

/**
 * @member {Number} idpreco
 */
ReservaPaymentJsonld.prototype.idpreco = undefined;

/**
 * @member {Number} idreserva
 */
ReservaPaymentJsonld.prototype.idreserva = undefined;

/**
 * @member {Date} data
 */
ReservaPaymentJsonld.prototype.data = undefined;
