/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The ReservaState model module.
 * @module model/ReservaState
 * @version 0.0.0
 */
export class ReservaState {
  /**
   * Constructs a new <code>ReservaState</code>.
   * ReservaState
   * @alias module:model/ReservaState
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>ReservaState</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReservaState} obj Optional instance to populate.
   * @return {module:model/ReservaState} The populated <code>ReservaState</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReservaState();
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("state"))
        obj.state = ApiClient.convertToType(data["state"], "String");
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ReservaState.prototype.id = undefined;

/**
 * @member {String} state
 */
ReservaState.prototype.state = undefined;
