/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The ReservaStateJsonld model module.
 * @module model/ReservaStateJsonld
 * @version 0.0.0
 */
export class ReservaStateJsonld {
  /**
   * Constructs a new <code>ReservaStateJsonld</code>.
   * ReservaState
   * @alias module:model/ReservaStateJsonld
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>ReservaStateJsonld</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReservaStateJsonld} obj Optional instance to populate.
   * @return {module:model/ReservaStateJsonld} The populated <code>ReservaStateJsonld</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReservaStateJsonld();
      if (data.hasOwnProperty("@context"))
        obj.context = ApiClient.convertToType(data["@context"], Object);
      if (data.hasOwnProperty("@id"))
        obj.id = ApiClient.convertToType(data["@id"], "String");
      if (data.hasOwnProperty("@type"))
        obj.type = ApiClient.convertToType(data["@type"], "String");
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("state"))
        obj.state = ApiClient.convertToType(data["state"], "String");
    }
    return obj;
  }
}

/**
 * @member {Object} context
 */
ReservaStateJsonld.prototype.context = undefined;

/**
 * @member {String} id
 */
ReservaStateJsonld.prototype.id = undefined;

/**
 * @member {String} type
 */
ReservaStateJsonld.prototype.type = undefined;

/**
 * @member {Number} id
 */
ReservaStateJsonld.prototype.id = undefined;

/**
 * @member {String} state
 */
ReservaStateJsonld.prototype.state = undefined;
