/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The Reserva model module.
 * @module model/Reserva
 * @version 0.0.0
 */
export class Reserva {
  /**
   * Constructs a new <code>Reserva</code>.
   * Reserva
   * @alias module:model/Reserva
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>Reserva</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Reserva} obj Optional instance to populate.
   * @return {module:model/Reserva} The populated <code>Reserva</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Reserva();
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("nPrereserva"))
        obj.nPrereserva = ApiClient.convertToType(
          data["nPrereserva"],
          "Number"
        );
      if (data.hasOwnProperty("reservado"))
        obj.reservado = ApiClient.convertToType(data["reservado"], "Boolean");
      if (data.hasOwnProperty("valor"))
        obj.valor = ApiClient.convertToType(data["valor"], "String");
      if (data.hasOwnProperty("nCheque"))
        obj.nCheque = ApiClient.convertToType(data["nCheque"], "String");
      if (data.hasOwnProperty("valorsinal"))
        obj.valorsinal = ApiClient.convertToType(data["valorsinal"], "String");
      if (data.hasOwnProperty("idcliente"))
        obj.idcliente = ApiClient.convertToType(data["idcliente"], "Number");
      if (data.hasOwnProperty("idpreco"))
        obj.idpreco = ApiClient.convertToType(data["idpreco"], "Number");
      if (data.hasOwnProperty("tipopagamento"))
        obj.tipopagamento = ApiClient.convertToType(
          data["tipopagamento"],
          "Number"
        );
      if (data.hasOwnProperty("nPagamento"))
        obj.nPagamento = ApiClient.convertToType(data["nPagamento"], "Number");
      if (data.hasOwnProperty("reservaState"))
        obj.reservaState = ApiClient.convertToType(
          data["reservaState"],
          "Number"
        );
      if (data.hasOwnProperty("data"))
        obj.data = ApiClient.convertToType(data["data"], "Date");
      if (data.hasOwnProperty("user"))
        obj.user = ApiClient.convertToType(data["user"], "String");
      if (data.hasOwnProperty("eventid"))
        obj.eventid = ApiClient.convertToType(data["eventid"], "String");
      if (data.hasOwnProperty("reservas"))
        obj.reservas = ApiClient.convertToType(data["reservas"], "String");
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Reserva.prototype.id = undefined;

/**
 * @member {Number} nPrereserva
 */
Reserva.prototype.nPrereserva = undefined;

/**
 * @member {Boolean} reservado
 * @default false
 */
Reserva.prototype.reservado = false;

/**
 * @member {String} valor
 * @default 'NULL'
 */
Reserva.prototype.valor = "NULL";

/**
 * @member {String} nCheque
 * @default 'NULL'
 */
Reserva.prototype.nCheque = "NULL";

/**
 * @member {String} valorsinal
 * @default 'NULL'
 */
Reserva.prototype.valorsinal = "NULL";

/**
 * @member {Number} idcliente
 */
Reserva.prototype.idcliente = undefined;

/**
 * @member {Number} idpreco
 */
Reserva.prototype.idpreco = undefined;

/**
 * @member {Number} tipopagamento
 */
Reserva.prototype.tipopagamento = undefined;

/**
 * @member {Number} nPagamento
 */
Reserva.prototype.nPagamento = undefined;

/**
 * @member {Number} reservaState
 */
Reserva.prototype.reservaState = undefined;

/**
 * @member {Date} data
 */
Reserva.prototype.data = undefined;

/**
 * @member {String} user
 * @default 'User'
 */
Reserva.prototype.user = "User";

/**
 * @member {String} eventid
 * @default 'NULL'
 */
Reserva.prototype.eventid = "NULL";

/**
 * @member {String} reservas
 */
Reserva.prototype.reservas = undefined;
