/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The TipoPagamentoJsonld model module.
 * @module model/TipoPagamentoJsonld
 * @version 0.0.0
 */
export class TipoPagamentoJsonld {
  /**
   * Constructs a new <code>TipoPagamentoJsonld</code>.
   * TipoPagamento
   * @alias module:model/TipoPagamentoJsonld
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>TipoPagamentoJsonld</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TipoPagamentoJsonld} obj Optional instance to populate.
   * @return {module:model/TipoPagamentoJsonld} The populated <code>TipoPagamentoJsonld</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TipoPagamentoJsonld();
      if (data.hasOwnProperty("@context"))
        obj.context = ApiClient.convertToType(data["@context"], Object);
      if (data.hasOwnProperty("@id"))
        obj.id = ApiClient.convertToType(data["@id"], "String");
      if (data.hasOwnProperty("@type"))
        obj.type = ApiClient.convertToType(data["@type"], "String");
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("tipoPagamento"))
        obj.tipoPagamento = ApiClient.convertToType(
          data["tipoPagamento"],
          "String"
        );
    }
    return obj;
  }
}

/**
 * @member {Object} context
 */
TipoPagamentoJsonld.prototype.context = undefined;

/**
 * @member {String} id
 */
TipoPagamentoJsonld.prototype.id = undefined;

/**
 * @member {String} type
 */
TipoPagamentoJsonld.prototype.type = undefined;

/**
 * @member {Number} id
 */
TipoPagamentoJsonld.prototype.id = undefined;

/**
 * @member {String} tipoPagamento
 */
TipoPagamentoJsonld.prototype.tipoPagamento = undefined;
