/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The Tipo model module.
 * @module model/Tipo
 * @version 0.0.0
 */
export class Tipo {
  /**
   * Constructs a new <code>Tipo</code>.
   * Tipo
   * @alias module:model/Tipo
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>Tipo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tipo} obj Optional instance to populate.
   * @return {module:model/Tipo} The populated <code>Tipo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Tipo();
      if (data.hasOwnProperty("idTipo"))
        obj.idTipo = ApiClient.convertToType(data["idTipo"], "Number");
      if (data.hasOwnProperty("tipo"))
        obj.tipo = ApiClient.convertToType(data["tipo"], "String");
    }
    return obj;
  }
}

/**
 * @member {Number} idTipo
 */
Tipo.prototype.idTipo = undefined;

/**
 * @member {String} tipo
 */
Tipo.prototype.tipo = undefined;
