/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The TipoAlojamento model module.
 * @module model/TipoAlojamento
 * @version 0.0.0
 */
export class TipoAlojamento {
  /**
   * Constructs a new <code>TipoAlojamento</code>.
   * TipoAlojamento
   * @alias module:model/TipoAlojamento
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>TipoAlojamento</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TipoAlojamento} obj Optional instance to populate.
   * @return {module:model/TipoAlojamento} The populated <code>TipoAlojamento</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TipoAlojamento();
      if (data.hasOwnProperty("idTipoAlojamento"))
        obj.idTipoAlojamento = ApiClient.convertToType(
          data["idTipoAlojamento"],
          "Number"
        );
      if (data.hasOwnProperty("tipoAlojamento"))
        obj.tipoAlojamento = ApiClient.convertToType(
          data["tipoAlojamento"],
          "String"
        );
    }
    return obj;
  }
}

/**
 * @member {Number} idTipoAlojamento
 */
TipoAlojamento.prototype.idTipoAlojamento = undefined;

/**
 * @member {String} tipoAlojamento
 */
TipoAlojamento.prototype.tipoAlojamento = undefined;
