/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The TipoAlojamentoJsonld model module.
 * @module model/TipoAlojamentoJsonld
 * @version 0.0.0
 */
export class TipoAlojamentoJsonld {
  /**
   * Constructs a new <code>TipoAlojamentoJsonld</code>.
   * TipoAlojamento
   * @alias module:model/TipoAlojamentoJsonld
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>TipoAlojamentoJsonld</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TipoAlojamentoJsonld} obj Optional instance to populate.
   * @return {module:model/TipoAlojamentoJsonld} The populated <code>TipoAlojamentoJsonld</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TipoAlojamentoJsonld();
      if (data.hasOwnProperty("@context"))
        obj.context = ApiClient.convertToType(data["@context"], Object);
      if (data.hasOwnProperty("@id"))
        obj.id = ApiClient.convertToType(data["@id"], "String");
      if (data.hasOwnProperty("@type"))
        obj.type = ApiClient.convertToType(data["@type"], "String");
      if (data.hasOwnProperty("idTipoAlojamento"))
        obj.idTipoAlojamento = ApiClient.convertToType(
          data["idTipoAlojamento"],
          "Number"
        );
      if (data.hasOwnProperty("tipoAlojamento"))
        obj.tipoAlojamento = ApiClient.convertToType(
          data["tipoAlojamento"],
          "String"
        );
    }
    return obj;
  }
}

/**
 * @member {Object} context
 */
TipoAlojamentoJsonld.prototype.context = undefined;

/**
 * @member {String} id
 */
TipoAlojamentoJsonld.prototype.id = undefined;

/**
 * @member {String} type
 */
TipoAlojamentoJsonld.prototype.type = undefined;

/**
 * @member {Number} idTipoAlojamento
 */
TipoAlojamentoJsonld.prototype.idTipoAlojamento = undefined;

/**
 * @member {String} tipoAlojamento
 */
TipoAlojamentoJsonld.prototype.tipoAlojamento = undefined;
