/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import { InlineResponse20015 } from "../model/InlineResponse20015";
import { Proprietariocancelissue } from "../model/Proprietariocancelissue";
import { ProprietariocancelissueJsonld } from "../model/ProprietariocancelissueJsonld";

/**
 * Proprietariocancelissue service.
 * @module api/ProprietariocancelissueApi
 * @version 0.0.0
 */
export class ProprietariocancelissueApi {
  /**
    * Constructs a new ProprietariocancelissueApi. 
    * @alias module:api/ProprietariocancelissueApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Callback function to receive the result of the deleteProprietariocancelissueItem operation.
   * @callback moduleapi/ProprietariocancelissueApi~deleteProprietariocancelissueItemCallback
   * @param {String} error Error message, if any.
   * @param data This operation does not return a value.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Removes the Proprietariocancelissue resource.
   * Removes the Proprietariocancelissue resource.
   * @param {String} id Resource identifier
   * @param {module:api/ProprietariocancelissueApi~deleteProprietariocancelissueItemCallback} callback The callback function, accepting three arguments: error, data, response
   */
  deleteProprietariocancelissueItem(id, callback) {
    let postBody = null;
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling deleteProprietariocancelissueItem"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = [];
    let returnType = null;

    return this.apiClient.callApi(
      "/api/proprietariocancelissues/{id}",
      "DELETE",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
  /**
   * Callback function to receive the result of the getProprietariocancelissueCollection operation.
   * @callback moduleapi/ProprietariocancelissueApi~getProprietariocancelissueCollectionCallback
   * @param {String} error Error message, if any.
   * @param {module:model/InlineResponse20015{ data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Retrieves the collection of Proprietariocancelissue resources.
   * Retrieves the collection of Proprietariocancelissue resources.
   * @param {Object} opts Optional parameters
   * @param {Number} opts.page The collection page number (default to <.>)
   * @param {module:api/ProprietariocancelissueApi~getProprietariocancelissueCollectionCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
   */
  getProprietariocancelissueCollection(opts, callback) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {};
    let queryParams = {
      page: opts["page"],
    };
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/ld+json", "application/json", "text/html"];
    let returnType = InlineResponse20015;

    return this.apiClient.callApi(
      "/api/proprietariocancelissues",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
  /**
   * Callback function to receive the result of the getProprietariocancelissueItem operation.
   * @callback moduleapi/ProprietariocancelissueApi~getProprietariocancelissueItemCallback
   * @param {String} error Error message, if any.
   * @param {module:model/ProprietariocancelissueJsonld{ data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Retrieves a Proprietariocancelissue resource.
   * Retrieves a Proprietariocancelissue resource.
   * @param {String} id Resource identifier
   * @param {module:api/ProprietariocancelissueApi~getProprietariocancelissueItemCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
   */
  getProprietariocancelissueItem(id, callback) {
    let postBody = null;
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling getProprietariocancelissueItem"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/ld+json", "application/json", "text/html"];
    let returnType = ProprietariocancelissueJsonld;

    return this.apiClient.callApi(
      "/api/proprietariocancelissues/{id}",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
  /**
   * Callback function to receive the result of the patchProprietariocancelissueItem operation.
   * @callback moduleapi/ProprietariocancelissueApi~patchProprietariocancelissueItemCallback
   * @param {String} error Error message, if any.
   * @param {module:model/ProprietariocancelissueJsonld{ data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Updates the Proprietariocancelissue resource.
   * Updates the Proprietariocancelissue resource.
   * @param {module:model/Proprietariocancelissue} body The updated Proprietariocancelissue resource
   * @param {String} id Resource identifier
   * @param {module:api/ProprietariocancelissueApi~patchProprietariocancelissueItemCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
   */
  patchProprietariocancelissueItem(body, id, callback) {
    let postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error(
        "Missing the required parameter 'body' when calling patchProprietariocancelissueItem"
      );
    }
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling patchProprietariocancelissueItem"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = ["application/merge-patch+json"];
    let accepts = ["application/ld+json", "application/json", "text/html"];
    let returnType = ProprietariocancelissueJsonld;

    return this.apiClient.callApi(
      "/api/proprietariocancelissues/{id}",
      "PATCH",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
  /**
   * Callback function to receive the result of the postProprietariocancelissueCollection operation.
   * @callback moduleapi/ProprietariocancelissueApi~postProprietariocancelissueCollectionCallback
   * @param {String} error Error message, if any.
   * @param {module:model/ProprietariocancelissueJsonld{ data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Creates a Proprietariocancelissue resource.
   * Creates a Proprietariocancelissue resource.
   * @param {module:model/ProprietariocancelissueJsonld} body The new Proprietariocancelissue resource
   * @param {module:api/ProprietariocancelissueApi~postProprietariocancelissueCollectionCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
   */
  postProprietariocancelissueCollection(body, callback) {
    let postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error(
        "Missing the required parameter 'body' when calling postProprietariocancelissueCollection"
      );
    }

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = ["application/ld+json", "application/json", "text/html"];
    let accepts = ["application/ld+json", "application/json", "text/html"];
    let returnType = ProprietariocancelissueJsonld;

    return this.apiClient.callApi(
      "/api/proprietariocancelissues",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
  /**
   * Callback function to receive the result of the putProprietariocancelissueItem operation.
   * @callback moduleapi/ProprietariocancelissueApi~putProprietariocancelissueItemCallback
   * @param {String} error Error message, if any.
   * @param {module:model/ProprietariocancelissueJsonld{ data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Replaces the Proprietariocancelissue resource.
   * Replaces the Proprietariocancelissue resource.
   * @param {module:model/ProprietariocancelissueJsonld} body The updated Proprietariocancelissue resource
   * @param {String} id Resource identifier
   * @param {module:api/ProprietariocancelissueApi~putProprietariocancelissueItemCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
   */
  putProprietariocancelissueItem(body, id, callback) {
    let postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error(
        "Missing the required parameter 'body' when calling putProprietariocancelissueItem"
      );
    }
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling putProprietariocancelissueItem"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = ["application/ld+json", "application/json", "text/html"];
    let accepts = ["application/ld+json", "application/json", "text/html"];
    let returnType = ProprietariocancelissueJsonld;

    return this.apiClient.callApi(
      "/api/proprietariocancelissues/{id}",
      "PUT",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
}
