/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import { InlineResponse20020 } from "../model/InlineResponse20020";
import { Sourcemessage } from "../model/Sourcemessage";
import { SourcemessageJsonld } from "../model/SourcemessageJsonld";

/**
 * Sourcemessage service.
 * @module api/SourcemessageApi
 * @version 0.0.0
 */
export class SourcemessageApi {
  /**
    * Constructs a new SourcemessageApi. 
    * @alias module:api/SourcemessageApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Callback function to receive the result of the deleteSourcemessageItem operation.
   * @callback moduleapi/SourcemessageApi~deleteSourcemessageItemCallback
   * @param {String} error Error message, if any.
   * @param data This operation does not return a value.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Removes the Sourcemessage resource.
   * Removes the Sourcemessage resource.
   * @param {String} id Resource identifier
   * @param {module:api/SourcemessageApi~deleteSourcemessageItemCallback} callback The callback function, accepting three arguments: error, data, response
   */
  deleteSourcemessageItem(id, callback) {
    let postBody = null;
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling deleteSourcemessageItem"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = [];
    let returnType = null;

    return this.apiClient.callApi(
      "/api/sourcemessages/{id}",
      "DELETE",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
  /**
   * Callback function to receive the result of the getSourcemessageCollection operation.
   * @callback moduleapi/SourcemessageApi~getSourcemessageCollectionCallback
   * @param {String} error Error message, if any.
   * @param {module:model/InlineResponse20020{ data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Retrieves the collection of Sourcemessage resources.
   * Retrieves the collection of Sourcemessage resources.
   * @param {Object} opts Optional parameters
   * @param {Number} opts.page The collection page number (default to <.>)
   * @param {module:api/SourcemessageApi~getSourcemessageCollectionCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
   */
  getSourcemessageCollection(opts, callback) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {};
    let queryParams = {
      page: opts["page"],
    };
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/ld+json", "application/json", "text/html"];
    let returnType = InlineResponse20020;

    return this.apiClient.callApi(
      "/api/sourcemessages",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
  /**
   * Callback function to receive the result of the getSourcemessageItem operation.
   * @callback moduleapi/SourcemessageApi~getSourcemessageItemCallback
   * @param {String} error Error message, if any.
   * @param {module:model/SourcemessageJsonld{ data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Retrieves a Sourcemessage resource.
   * Retrieves a Sourcemessage resource.
   * @param {String} id Resource identifier
   * @param {module:api/SourcemessageApi~getSourcemessageItemCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
   */
  getSourcemessageItem(id, callback) {
    let postBody = null;
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling getSourcemessageItem"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/ld+json", "application/json", "text/html"];
    let returnType = SourcemessageJsonld;

    return this.apiClient.callApi(
      "/api/sourcemessages/{id}",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
  /**
   * Callback function to receive the result of the patchSourcemessageItem operation.
   * @callback moduleapi/SourcemessageApi~patchSourcemessageItemCallback
   * @param {String} error Error message, if any.
   * @param {module:model/SourcemessageJsonld{ data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Updates the Sourcemessage resource.
   * Updates the Sourcemessage resource.
   * @param {module:model/Sourcemessage} body The updated Sourcemessage resource
   * @param {String} id Resource identifier
   * @param {module:api/SourcemessageApi~patchSourcemessageItemCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
   */
  patchSourcemessageItem(body, id, callback) {
    let postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error(
        "Missing the required parameter 'body' when calling patchSourcemessageItem"
      );
    }
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling patchSourcemessageItem"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = ["application/merge-patch+json"];
    let accepts = ["application/ld+json", "application/json", "text/html"];
    let returnType = SourcemessageJsonld;

    return this.apiClient.callApi(
      "/api/sourcemessages/{id}",
      "PATCH",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
  /**
   * Callback function to receive the result of the postSourcemessageCollection operation.
   * @callback moduleapi/SourcemessageApi~postSourcemessageCollectionCallback
   * @param {String} error Error message, if any.
   * @param {module:model/SourcemessageJsonld{ data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Creates a Sourcemessage resource.
   * Creates a Sourcemessage resource.
   * @param {module:model/SourcemessageJsonld} body The new Sourcemessage resource
   * @param {module:api/SourcemessageApi~postSourcemessageCollectionCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
   */
  postSourcemessageCollection(body, callback) {
    let postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error(
        "Missing the required parameter 'body' when calling postSourcemessageCollection"
      );
    }

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = ["application/ld+json", "application/json", "text/html"];
    let accepts = ["application/ld+json", "application/json", "text/html"];
    let returnType = SourcemessageJsonld;

    return this.apiClient.callApi(
      "/api/sourcemessages",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
  /**
   * Callback function to receive the result of the putSourcemessageItem operation.
   * @callback moduleapi/SourcemessageApi~putSourcemessageItemCallback
   * @param {String} error Error message, if any.
   * @param {module:model/SourcemessageJsonld{ data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Replaces the Sourcemessage resource.
   * Replaces the Sourcemessage resource.
   * @param {module:model/SourcemessageJsonld} body The updated Sourcemessage resource
   * @param {String} id Resource identifier
   * @param {module:api/SourcemessageApi~putSourcemessageItemCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
   */
  putSourcemessageItem(body, id, callback) {
    let postBody = body;
    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error(
        "Missing the required parameter 'body' when calling putSourcemessageItem"
      );
    }
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling putSourcemessageItem"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = ["application/ld+json", "application/json", "text/html"];
    let accepts = ["application/ld+json", "application/json", "text/html"];
    let returnType = SourcemessageJsonld;

    return this.apiClient.callApi(
      "/api/sourcemessages/{id}",
      "PUT",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
}
