/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  describe("(package)", function () {
    describe("TipoAlojamento", function () {
      beforeEach(function () {
        instance = new SwaggerJsClient.TipoAlojamento();
      });

      it("should create an instance of TipoAlojamento", function () {
        // TODO: update the code to test TipoAlojamento
        expect(instance).to.be.a(SwaggerJsClient.TipoAlojamento);
      });

      it('should have the property idTipoAlojamento (base name: "idTipoAlojamento")', function () {
        // TODO: update the code to test the property idTipoAlojamento
        expect(instance).to.have.property("idTipoAlojamento");
        // expect(instance.idTipoAlojamento).to.be(expectedValueLiteral);
      });

      it('should have the property tipoAlojamento (base name: "tipoAlojamento")', function () {
        // TODO: update the code to test the property tipoAlojamento
        expect(instance).to.have.property("tipoAlojamento");
        // expect(instance.tipoAlojamento).to.be(expectedValueLiteral);
      });
    });
  });
});
