/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.ClienteApi();
  });

  describe("(package)", function () {
    describe("ClienteApi", function () {
      describe("deleteClienteItem", function () {
        it("should call deleteClienteItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteClienteItem call
          /*

          instance.deleteClienteItem(clienteid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getClienteCollection", function () {
        it("should call getClienteCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getClienteCollection call and complete the assertions
          /*
          var opts = {};

          instance.getClienteCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse2003);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getClienteItem", function () {
        it("should call getClienteItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getClienteItem call and complete the assertions
          /*

          instance.getClienteItem(clienteid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ClienteJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchClienteItem", function () {
        it("should call patchClienteItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchClienteItem call and complete the assertions
          /*

          instance.patchClienteItem(body, clienteid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ClienteJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postClienteCollection", function () {
        it("should call postClienteCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postClienteCollection call and complete the assertions
          /*

          instance.postClienteCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ClienteJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putClienteItem", function () {
        it("should call putClienteItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putClienteItem call and complete the assertions
          /*

          instance.putClienteItem(body, clienteid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ClienteJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
