/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.EstadiaMinimaApi();
  });

  describe("(package)", function () {
    describe("EstadiaMinimaApi", function () {
      describe("deleteEstadiaMinimaItem", function () {
        it("should call deleteEstadiaMinimaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteEstadiaMinimaItem call
          /*

          instance.deleteEstadiaMinimaItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getEstadiaMinimaCollection", function () {
        it("should call getEstadiaMinimaCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getEstadiaMinimaCollection call and complete the assertions
          /*
          var opts = {};

          instance.getEstadiaMinimaCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse2006);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getEstadiaMinimaItem", function () {
        it("should call getEstadiaMinimaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getEstadiaMinimaItem call and complete the assertions
          /*

          instance.getEstadiaMinimaItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.EstadiaMinimaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchEstadiaMinimaItem", function () {
        it("should call patchEstadiaMinimaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchEstadiaMinimaItem call and complete the assertions
          /*

          instance.patchEstadiaMinimaItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.EstadiaMinimaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postEstadiaMinimaCollection", function () {
        it("should call postEstadiaMinimaCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postEstadiaMinimaCollection call and complete the assertions
          /*

          instance.postEstadiaMinimaCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.EstadiaMinimaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putEstadiaMinimaItem", function () {
        it("should call putEstadiaMinimaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putEstadiaMinimaItem call and complete the assertions
          /*

          instance.putEstadiaMinimaItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.EstadiaMinimaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
