/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.FeedbackcomentApi();
  });

  describe("(package)", function () {
    describe("FeedbackcomentApi", function () {
      describe("deleteFeedbackcomentItem", function () {
        it("should call deleteFeedbackcomentItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteFeedbackcomentItem call
          /*

          instance.deleteFeedbackcomentItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getFeedbackcomentCollection", function () {
        it("should call getFeedbackcomentCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getFeedbackcomentCollection call and complete the assertions
          /*
          var opts = {};

          instance.getFeedbackcomentCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse2008);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getFeedbackcomentItem", function () {
        it("should call getFeedbackcomentItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getFeedbackcomentItem call and complete the assertions
          /*

          instance.getFeedbackcomentItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.FeedbackcomentJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchFeedbackcomentItem", function () {
        it("should call patchFeedbackcomentItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchFeedbackcomentItem call and complete the assertions
          /*

          instance.patchFeedbackcomentItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.FeedbackcomentJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postFeedbackcomentCollection", function () {
        it("should call postFeedbackcomentCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postFeedbackcomentCollection call and complete the assertions
          /*

          instance.postFeedbackcomentCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.FeedbackcomentJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putFeedbackcomentItem", function () {
        it("should call putFeedbackcomentItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putFeedbackcomentItem call and complete the assertions
          /*

          instance.putFeedbackcomentItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.FeedbackcomentJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
