/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.FeedbackApi();
  });

  describe("(package)", function () {
    describe("FeedbackApi", function () {
      describe("deleteFeedbackItem", function () {
        it("should call deleteFeedbackItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteFeedbackItem call
          /*

          instance.deleteFeedbackItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getFeedbackCollection", function () {
        it("should call getFeedbackCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getFeedbackCollection call and complete the assertions
          /*
          var opts = {};

          instance.getFeedbackCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse2007);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getFeedbackItem", function () {
        it("should call getFeedbackItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getFeedbackItem call and complete the assertions
          /*

          instance.getFeedbackItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.FeedbackJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchFeedbackItem", function () {
        it("should call patchFeedbackItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchFeedbackItem call and complete the assertions
          /*

          instance.patchFeedbackItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.FeedbackJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postFeedbackCollection", function () {
        it("should call postFeedbackCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postFeedbackCollection call and complete the assertions
          /*

          instance.postFeedbackCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.FeedbackJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putFeedbackItem", function () {
        it("should call putFeedbackItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putFeedbackItem call and complete the assertions
          /*

          instance.putFeedbackItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.FeedbackJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
