/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.MessageApi();
  });

  describe("(package)", function () {
    describe("MessageApi", function () {
      describe("deleteMessageItem", function () {
        it("should call deleteMessageItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteMessageItem call
          /*

          instance.deleteMessageItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getMessageCollection", function () {
        it("should call getMessageCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getMessageCollection call and complete the assertions
          /*
          var opts = {};

          instance.getMessageCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse2009);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getMessageItem", function () {
        it("should call getMessageItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getMessageItem call and complete the assertions
          /*

          instance.getMessageItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.MessageJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchMessageItem", function () {
        it("should call patchMessageItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchMessageItem call and complete the assertions
          /*

          instance.patchMessageItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.MessageJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postMessageCollection", function () {
        it("should call postMessageCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postMessageCollection call and complete the assertions
          /*

          instance.postMessageCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.MessageJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putMessageItem", function () {
        it("should call putMessageItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putMessageItem call and complete the assertions
          /*

          instance.putMessageItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.MessageJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
