/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.PeriodoApi();
  });

  describe("(package)", function () {
    describe("PeriodoApi", function () {
      describe("deletePeriodoItem", function () {
        it("should call deletePeriodoItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deletePeriodoItem call
          /*

          instance.deletePeriodoItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getPeriodoCollection", function () {
        it("should call getPeriodoCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getPeriodoCollection call and complete the assertions
          /*
          var opts = {};

          instance.getPeriodoCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse20012);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getPeriodoItem", function () {
        it("should call getPeriodoItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getPeriodoItem call and complete the assertions
          /*

          instance.getPeriodoItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.PeriodoJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchPeriodoItem", function () {
        it("should call patchPeriodoItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchPeriodoItem call and complete the assertions
          /*

          instance.patchPeriodoItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.PeriodoJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postPeriodoCollection", function () {
        it("should call postPeriodoCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postPeriodoCollection call and complete the assertions
          /*

          instance.postPeriodoCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.PeriodoJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putPeriodoItem", function () {
        it("should call putPeriodoItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putPeriodoItem call and complete the assertions
          /*

          instance.putPeriodoItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.PeriodoJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
