/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.ProprietarioApi();
  });

  describe("(package)", function () {
    describe("ProprietarioApi", function () {
      describe("deleteProprietarioItem", function () {
        it("should call deleteProprietarioItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteProprietarioItem call
          /*

          instance.deleteProprietarioItem(propid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getProprietarioCollection", function () {
        it("should call getProprietarioCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getProprietarioCollection call and complete the assertions
          /*
          var opts = {};

          instance.getProprietarioCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse20016);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getProprietarioItem", function () {
        it("should call getProprietarioItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getProprietarioItem call and complete the assertions
          /*

          instance.getProprietarioItem(propid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ProprietarioJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchProprietarioItem", function () {
        it("should call patchProprietarioItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchProprietarioItem call and complete the assertions
          /*

          instance.patchProprietarioItem(body, propid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ProprietarioJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postProprietarioCollection", function () {
        it("should call postProprietarioCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postProprietarioCollection call and complete the assertions
          /*

          instance.postProprietarioCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ProprietarioJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putProprietarioItem", function () {
        it("should call putProprietarioItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putProprietarioItem call and complete the assertions
          /*

          instance.putProprietarioItem(body, propid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ProprietarioJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
