/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.ProprietariocancelissueApi();
  });

  describe("(package)", function () {
    describe("ProprietariocancelissueApi", function () {
      describe("deleteProprietariocancelissueItem", function () {
        it("should call deleteProprietariocancelissueItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteProprietariocancelissueItem call
          /*

          instance.deleteProprietariocancelissueItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getProprietariocancelissueCollection", function () {
        it("should call getProprietariocancelissueCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getProprietariocancelissueCollection call and complete the assertions
          /*
          var opts = {};

          instance.getProprietariocancelissueCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse20015);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getProprietariocancelissueItem", function () {
        it("should call getProprietariocancelissueItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getProprietariocancelissueItem call and complete the assertions
          /*

          instance.getProprietariocancelissueItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ProprietariocancelissueJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchProprietariocancelissueItem", function () {
        it("should call patchProprietariocancelissueItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchProprietariocancelissueItem call and complete the assertions
          /*

          instance.patchProprietariocancelissueItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ProprietariocancelissueJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postProprietariocancelissueCollection", function () {
        it("should call postProprietariocancelissueCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postProprietariocancelissueCollection call and complete the assertions
          /*

          instance.postProprietariocancelissueCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ProprietariocancelissueJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putProprietariocancelissueItem", function () {
        it("should call putProprietariocancelissueItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putProprietariocancelissueItem call and complete the assertions
          /*

          instance.putProprietariocancelissueItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ProprietariocancelissueJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
