/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.ReservaApi();
  });

  describe("(package)", function () {
    describe("ReservaApi", function () {
      describe("deleteReservaItem", function () {
        it("should call deleteReservaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteReservaItem call
          /*

          instance.deleteReservaItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getReservaCollection", function () {
        it("should call getReservaCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getReservaCollection call and complete the assertions
          /*
          var opts = {};

          instance.getReservaCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse20019);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getReservaItem", function () {
        it("should call getReservaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getReservaItem call and complete the assertions
          /*

          instance.getReservaItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ReservaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchReservaItem", function () {
        it("should call patchReservaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchReservaItem call and complete the assertions
          /*

          instance.patchReservaItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ReservaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postReservaCollection", function () {
        it("should call postReservaCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postReservaCollection call and complete the assertions
          /*

          instance.postReservaCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ReservaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putReservaItem", function () {
        it("should call putReservaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putReservaItem call and complete the assertions
          /*

          instance.putReservaItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ReservaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
