/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.ReservaStateApi();
  });

  describe("(package)", function () {
    describe("ReservaStateApi", function () {
      describe("deleteReservaStateItem", function () {
        it("should call deleteReservaStateItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteReservaStateItem call
          /*

          instance.deleteReservaStateItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getReservaStateCollection", function () {
        it("should call getReservaStateCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getReservaStateCollection call and complete the assertions
          /*
          var opts = {};

          instance.getReservaStateCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse20018);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getReservaStateItem", function () {
        it("should call getReservaStateItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getReservaStateItem call and complete the assertions
          /*

          instance.getReservaStateItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ReservaStateJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchReservaStateItem", function () {
        it("should call patchReservaStateItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchReservaStateItem call and complete the assertions
          /*

          instance.patchReservaStateItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ReservaStateJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postReservaStateCollection", function () {
        it("should call postReservaStateCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postReservaStateCollection call and complete the assertions
          /*

          instance.postReservaStateCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ReservaStateJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putReservaStateItem", function () {
        it("should call putReservaStateItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putReservaStateItem call and complete the assertions
          /*

          instance.putReservaStateItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.ReservaStateJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
