/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.SourcemessageApi();
  });

  describe("(package)", function () {
    describe("SourcemessageApi", function () {
      describe("deleteSourcemessageItem", function () {
        it("should call deleteSourcemessageItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteSourcemessageItem call
          /*

          instance.deleteSourcemessageItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getSourcemessageCollection", function () {
        it("should call getSourcemessageCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getSourcemessageCollection call and complete the assertions
          /*
          var opts = {};

          instance.getSourcemessageCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse20020);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getSourcemessageItem", function () {
        it("should call getSourcemessageItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getSourcemessageItem call and complete the assertions
          /*

          instance.getSourcemessageItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.SourcemessageJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchSourcemessageItem", function () {
        it("should call patchSourcemessageItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchSourcemessageItem call and complete the assertions
          /*

          instance.patchSourcemessageItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.SourcemessageJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postSourcemessageCollection", function () {
        it("should call postSourcemessageCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postSourcemessageCollection call and complete the assertions
          /*

          instance.postSourcemessageCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.SourcemessageJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putSourcemessageItem", function () {
        it("should call putSourcemessageItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putSourcemessageItem call and complete the assertions
          /*

          instance.putSourcemessageItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.SourcemessageJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
