/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.TipoApi();
  });

  describe("(package)", function () {
    describe("TipoApi", function () {
      describe("deleteTipoItem", function () {
        it("should call deleteTipoItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteTipoItem call
          /*

          instance.deleteTipoItem(idTipo, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getTipoCollection", function () {
        it("should call getTipoCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getTipoCollection call and complete the assertions
          /*
          var opts = {};

          instance.getTipoCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse20023);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getTipoItem", function () {
        it("should call getTipoItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getTipoItem call and complete the assertions
          /*

          instance.getTipoItem(idTipo, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.TipoJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchTipoItem", function () {
        it("should call patchTipoItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchTipoItem call and complete the assertions
          /*

          instance.patchTipoItem(body, idTipo, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.TipoJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postTipoCollection", function () {
        it("should call postTipoCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postTipoCollection call and complete the assertions
          /*

          instance.postTipoCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.TipoJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putTipoItem", function () {
        it("should call putTipoItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putTipoItem call and complete the assertions
          /*

          instance.putTipoItem(body, idTipo, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.TipoJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
