/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
})(this, function (expect, SwaggerJsClient) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new SwaggerJsClient.VisitaApi();
  });

  describe("(package)", function () {
    describe("VisitaApi", function () {
      describe("deleteVisitaItem", function () {
        it("should call deleteVisitaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for deleteVisitaItem call
          /*

          instance.deleteVisitaItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getVisitaCollection", function () {
        it("should call getVisitaCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for getVisitaCollection call and complete the assertions
          /*
          var opts = {};

          instance.getVisitaCollection(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.InlineResponse20024);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("getVisitaItem", function () {
        it("should call getVisitaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for getVisitaItem call and complete the assertions
          /*

          instance.getVisitaItem(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.VisitaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("patchVisitaItem", function () {
        it("should call patchVisitaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for patchVisitaItem call and complete the assertions
          /*

          instance.patchVisitaItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.VisitaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("postVisitaCollection", function () {
        it("should call postVisitaCollection successfully", function (done) {
          // TODO: uncomment, update parameter values for postVisitaCollection call and complete the assertions
          /*

          instance.postVisitaCollection(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.VisitaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe("putVisitaItem", function () {
        it("should call putVisitaItem successfully", function (done) {
          // TODO: uncomment, update parameter values for putVisitaItem call and complete the assertions
          /*

          instance.putVisitaItem(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerJsClient.VisitaJsonld);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });
});
